// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz6FUH5PEzqdq-LVvcpVnAAs2jsrYr4uI',
    appId: '1:255731705169:web:0cba0edd30e269231f1f70',
    messagingSenderId: '255731705169',
    projectId: 'crono-shoes',
    authDomain: 'crono-shoes.firebaseapp.com',
    storageBucket: 'crono-shoes.appspot.com',
    measurementId: 'G-6ZD1KJM2VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQOfPB48g-sCxhGQHIEPYAY1ZFaQKclqE',
    appId: '1:255731705169:android:f80994b3d7d9bad81f1f70',
    messagingSenderId: '255731705169',
    projectId: 'crono-shoes',
    storageBucket: 'crono-shoes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALKUpOfCy-bZJ3kPbItgx9x7t9fZwsw7E',
    appId: '1:255731705169:ios:fcd91daf4edb3da31f1f70',
    messagingSenderId: '255731705169',
    projectId: 'crono-shoes',
    storageBucket: 'crono-shoes.appspot.com',
    iosClientId: '255731705169-54vnm5pgn5f01rsc0a1fa7it69gtnvio.apps.googleusercontent.com',
    iosBundleId: 'com.example.cronoshoes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALKUpOfCy-bZJ3kPbItgx9x7t9fZwsw7E',
    appId: '1:255731705169:ios:fcd91daf4edb3da31f1f70',
    messagingSenderId: '255731705169',
    projectId: 'crono-shoes',
    storageBucket: 'crono-shoes.appspot.com',
    iosClientId: '255731705169-54vnm5pgn5f01rsc0a1fa7it69gtnvio.apps.googleusercontent.com',
    iosBundleId: 'com.example.cronoshoes',
  );
}
